# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b449674f1fb169e62d97970a1a5d6efc53882c55218607ddcbce692f1ce8bbd503122e860d6173d0e003bbce0f5d14ec7b7cabf89f48cc581ee9f23e99c80c

test:
  secret_key_base: c0b884ea27bf2901f1c9b320e03c3408668eef960e5f2ec9b324bd4b97f9149ad8ec6b3477b6672e54b237232975de83b17c25afafa9e36be8439f2333ac7582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
